version: '3.8'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports: 
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
